version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    depends_on:
      - app
    networks:
      - asiayo-exercise

  app:
    build: .
    volumes:
      - .:/var/www/app
    networks:
      - asiayo-exercise

networks:
  asiayo-exercise:
    driver: bridge